### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/phpstan-wordpress#253]
What does it take to release 2.0.0?
Do we have v1-only features?
What is lost in v2?
https://github.com/szepeviktor/phpstan-wordpress/blob/3ffad2007d2adf01d7b77192fa264b6bed4e0846/composer.json#L15

**Comment by IanDelMar** [comment]
- v2 drops support for:
  - PHPStan 1.x (see #243),
  - PHP 7.2 (see #243), and
  - php-stubs/wordpress-stubs 6.6.1 and below (see #235; dynamic return type extensions have been moved to php-stubs/wordpress-stubs).

- Some dynamic return type extensions have been removed but were not moved to php-stubs/wordpress-stubs because they were either incorrect or indeterminable due to filterable arguments (see #235).

- `SzepeViktor\PHPStan\WordPress\HookDocsParamException` has been removed, as it was no longer in use (see #235).

- `StringOrArrayDynamicFunctionReturnTypeExtension` has been renamed to `EscSqlDynamicFunctionReturnTypeExtension` (see #237).

- Some early terminating calls have been moved to php-stubs/wordpress-stubs (see #238).

v1-only is support for PHP 7.2 and below, PHPStan below 2.x, older versions of WP(stubs), and dynamic return type extensions for functions with filterable arguments that were not transferred. (I am not certain whether the incorrect ones were fixed in v1 as well; I’ll verify this over the next few days).

I think it would be best to resolve the `_get_list_table()` issue (https://github.com/php-stubs/wordpress-stubs/issues/257) before releasing 2.0.0.

**Comment by LeTraceurSnork** [comment]
Could you please sync versions with PHPStan original package starting from v2 please? I mean, its a bit unhandy that PHPStan last v1 minor is 1.12 while this package is 1.3, it's a bit confusing

**Comment by szepeviktor** [comment]
> Could you please sync versions with PHPStan original package

Vote time!

**Comment by IanDelMar** [comment]
While I completely understand @LeTraceurSnork's point, halting progress on `szepeviktor/phpstan-wordpress` until PHPStan advances may not be in the best interests of the contributors and users. Any new feature, such as a return type extension, qualifies for a minor release, meaning we would need to wait for PHPStan’s next minor update. Fixes for extensions should be released as patches, but we would be unable to do so until PHPStan issues its next patch, minor, or even major release. After all, one look at the `composer.json` file tells you which PHPStan versions are applicable to the given version of `szepeviktor/phpstan-wordpress`.

**Comment by LeTraceurSnork** [comment]
What about extended semver like `X.Y.Z.P`, where P is suffix for your own version, and Z - is latest patch of parent package

**Comment by szepeviktor** [comment]
@LeTraceurSnork All I can promise you is when I see a *Merge* button I click on it.
It would be great not to be restricted by PHPStan's development.
Have you seen other extensions' release versions?

**Comment by LeTraceurSnork** [comment]
Ok, suggestion withdrawn 🙈

**Comment by szepeviktor** [comment]
Jump into the empty pool: https://github.com/szepeviktor/phpstan-wordpress/releases/tag/v2.0.0-rc.1
